### PR TITLE
a dialogue with {ra'o}

### PR DESCRIPTION
**Pull request by lagleki**
Example 7.39. 
A:	mi	ba	klama	le	zarci
A:	I	[future]	go-to	the	store.
A: I am going to the store.
B:	mi	nelci	le	si'o	mi	go'i
B:	I	like	the	concept-of	I	[repeat-last-bridi].
B: I like the idea of my going.
A:	do	go'e
A:	You	[repeat-last-bridi-but-one].
A: You'll go, too.
...
Example 7.45. 
mi ba lumci le mi karce
I will wash my car.
you might reply either:
Example 7.46. 
mi go'i
I will wash your car.
or:
Example 7.47. 
mi go'i ra'o
I will wash my car.

The ra'o forces the second mi from the original bridi to mean the new speaker rather than the former speaker. This means that go'e ra'o would be an acceptable alternative to do go'e in B's statement in Example 7.39.

----
 *After example 6.18 is a paragraph that quotes non-existent text from example 6.10. "go'e ra'o" should read "go'i ra'o" and "do go'e" should read "mi go'i"
** The correct correction is to replace "B's statement" with "A's second statement". ✔Cowan

### CODE REVIEW

**Comment by gr-g** [comment]
But if `go'e ra'o` replaces `do go'e`, `go'e` refers to A's first statement, and is spoken again by A. Adding `ra'o` does not have the desired effect then, right?

**Comment by lagleki** [comment]
It's possible that {ra'o} changes {mi} to {do}.

**Comment by lagleki** [comment]
Not vetoed according to https://mw.lojban.org/papri/CLL_1.2._Technical hence is allowed to be present in docbook-prince branch.

**Comment by Ntsekees** [comment]
I guess what was meant was maybe something along the lines of «if B said {go'e ra'o} instead of A saying {do go'e}, then the same claim would have been made (i.e. "B ba klama le zarci"), although by a different person.»

**Comment by Ntsekees** [comment]
But it'd be simpler to just delete that problematic sentence about example 7.39.

**Pull request merged**
