### PR TITLE
catalogue and anaphoric cmavo chapters pics

### PR DESCRIPTION
**Pull request by la-ninpre**
note on chapter-catalogue.svg: the original pic was so small, so i had to write that jokes by myself. if them are not appropriate, please, propose yours and i will remake this.

### CODE REVIEW

**Comment by lagleki** [comment]
https://github.com/lojban/cll/blob/docbook-prince/media/ch20%20scan%20cll%201.0.jpg

Here it is

**Comment by lagleki** [comment]
@la-ninpre 

https://github.com/lojban/cll/blob/docbook-prince/media/ch20%20scan%20cll%201.0.jpg

Here it is

**Comment by la-ninpre** [comment]
@lagleki

okay, thanks.

**Comment by lagleki** [comment]
I don't think you need to redo yours

**Pull request merged**
