### PR TITLE
make CLL available offline in a web browser

### PR DESCRIPTION
**Pull request by BenLubar**
add HTML5 cache manifest

### CODE REVIEW

**Comment by rlpowell** [comment]
Don't you need to also provide the manifest file for this to be of any use?

**Comment by BenLubar** [comment]
@rlpowell the manifest is part of the commit, but GitHub isn't showing it in the truncated list for some reason.

https://github.com/BenLubar/cll/blob/979ebe000bfec3109e2e6cc80864103dc36c25ef/cll.manifest

**Comment by lagleki** [comment]
The html generator should add links to the manifest. Pulling to gh-pages is useless.

**Comment by rlpowell** [comment]
As gleki said, we don't use that branch anymore.  However.  I think I've integrated into the main branch code that does what you want.  Please look at:

http://vrici.lojban.org/~rlpowell/media/public/cll_build/cll-xhtml_chapters/

http://vrici.lojban.org/~rlpowell/media/public/cll_build/cll-xhtml_nochunks/

http://vrici.lojban.org/~rlpowell/media/public/cll_build/cll-xhtml_sections/

(the three chunking levels), and let me know if they DTRT.

**Comment by BenLubar** [comment]
@rlpowell yes, it looks like they do the right thing.

**Pull request closed without merging**
